### ISSUE TITLE
Refactor query system to not be locked into the IReadModel interface

### ISSUE THREAD

**Issue by einari** [dolittle/Runtime#10]
The IReadModel should be moved to the C# SDK side

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1124151768439198)

**Comment by smithmx** [comment]
I just came in to register an issue on this.

Do we need the IReadModel generic restriction on IQueryFor<>?  It means you can't use anything that you don't own directly (we would need to mimic the structure of a third party object that we want to persist - maybe not a big deal) and that you cannot use a structure that you want to share (e.g.  a value object through the concepts project).

**Comment by einari** [comment]
We only have it as a marker interface, since we generate proxies. But we could be doing this in a different way by saying we generate for any type used as the generic parameter to IQueryFor<>
