### ISSUE TITLE
Parallel processing does not work

### ISSUE THREAD

**Issue by TomasEkeli** [dolittle/Runtime#102]
https://github.com/dolittle/Runtime/blob/1d10b4ce4967d8155d488bd40bd8d6a547a62c5e/Source/Events/Processing/ScopedEventProcessingHub.cs#L120

When we have several of the same event type in the same commit only the first event is actually processed.

To see the problem pull the Waterproof project origin/vessel_setup (commit 04e7132fabefc615eba4530ec3ac9ac9a8363a75) and run the following command: 

{
  "correlationId": "95886404-67D3-4615-8427-9FF218B66312",
  "type": "770682d0-28ff-4fa1-8fc8-a31b1251bd3e",
  "content": {
    "vessel_setup_id": "4FCB9F47-F847-4A97-875A-FAD0300B00A6",
    "boilers": [
      {
        "name": "Main boiler"
      }
    ],
    "hotwells": [
      {
        "name": "only hotwell"
      }
    ],
    "cascade_tanks": [],
    "deareators": [
      {
        "name": "asdf"
      }
    ],
    "condensate_systems": [
      {
        "name": "starboard condensate system"
      },
      {
        "name": "port condensate system"
      },
      {
        "name": "some other system"
      }
    ]
  }
}

The processor 4A926A09-4C5E-413E-A0E7-06311598E314 is only ever run once, and the read-model has only one condensate system (the first one).

**Comment by smithmx** [comment]
Spoke a bit to Tomas about this.  When there are multiple events of the same type on a commit, only the first is actually handled by the event processor.  I don't think we can actually use Parallel.ForEach here as the events really should be dispatched and processed in the correct order.

I'm also looking suspiciously at the code in 

https://github.com/dolittle/Runtime/blob/25b536ceb5b1ec3fc720f3f1721771db96e1c81b/Source/Events/Processing/ScopedEventProcessor.cs

The lock takes place in the internal ProcessEvent method but the check to see if the version is ok takes place in the Process method.  I think the lock should actually be in the Process method.

**Comment by woksin** [comment]
This was perhaps solved, @smithmx ?

**Comment by smithmx** [comment]
I think so.  I've got minor code changes and a few additional specs that I'll turn into a pull request.

**Comment by woksin** [comment]
You've fixes this now, @smithmx ?
