### ISSUE TITLE
OriginalContext does not contain the Claims when persisted

### ISSUE THREAD

**Issue by smithmx** [dolittle/Runtime#260]
I'm not sure if this is a bug in the MongoDB implementation, the Runtime or the SDK but when we persist events the OriginalContext of the Metadata always has an empty array of claims.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1129692567511136)

**Comment by einari** [comment]
Could this be GDPR concern? If there are PII as part of the claims.
