### ISSUE TITLE
Look into changing to Prometheus Client library

### ISSUE THREAD

**Issue by einari** [dolittle/Runtime#307]
We have an issue on the the Prometheus library we’re using today, which causes us to do some reflection magic to make it work for us, as described [here](https://github.com/prometheus-net/prometheus-net/issues/167).

There is an alternative library that started as a fork of what we’re using today but has changed amongst other things, this particular thing - plus added more features: https://github.com/PrometheusClientNet/Prometheus.Client

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1150974691082214)

**Comment by sanych-sun** [comment]
Hi everyone,

I'm co-maintainer of the Prometheus.Client. Thank you for interest to our library. We trying to build a strong community around the library. Please feel free to reach us with any questions, concerns or ideas.
