### ISSUE TITLE
Bson Serializer for immutable objects

### ISSUE THREAD

**Issue by smithmx** [dolittle/Runtime#31]

**Comment by einari** [comment]
This might belong in the Fundamentals - not Runtime. I could see for instance the introduction of a Bson serializer become interesting. 

Could you move it - tag it with 2.0.0 milestone and make it child of #26

**Comment by einari** [comment]
Also, we might be able to capture this with: https://github.com/dolittle/DotNET.Fundamentals/issues/2 - as mentioned in the issue: https://github.com/dolittle/DotNET.Fundamentals/issues/15
