### ISSUE TITLE
Redesign CommandResult

### ISSUE THREAD

**Issue by einari** [dolittle/Runtime#310]
We should slim down CommandResult to be much more relevant. Today we have separated into multiple different rule results and messages and we also bubble exceptions all the way up.
The latter represents a security risk as you can see in the frontend what code was faulty and deduct from that information that could be used to harm the system.

My suggestion is to break it down to basically a collection of instances of `BrokenRule` with the cause for breaking. Internally we could then have an encapsulation of exception and return it as a specific type of broken rule with the reason only holding the actual message.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1156332478138261)

**Comment by woksin** [comment]
Not relevant anymore
