### ISSUE TITLE
Use the execution context manager

### ISSUE THREAD

**Issue by woksin** [dolittle/Runtime#95]
I see there are currently many classes that have a dependency on the IExecutionContextManager, but only a few of them are using it. 

Now with the new resource system and strategy system that sets the tenant we need all parts of the system to use the correct execution context

**Comment by einari** [comment]
I've briefly looked through in Runtime and the use of `IExecutionContextManager` looks right to me. It is an integral part of the `EventHorizon` as it needs to be doing things in the correct context. Are you seeing anything in particular that is wrong that I've missed?

**Comment by woksin** [comment]
On a second go through I did not see the problem either... I think we can disregard this
